### ISSUE TITLE
Add two relevant papers

### ISSUE THREAD

**Issue by Wangpeiyi9979** [reasoning-survey/Awesome-Reasoning-Foundation-Models#1]
Hi, thanks for your excellent survey.

Please consider adding two relevant papers to your repository and paper:

[1] Title: Making Large Language Models Better Reasoners with Alignment
Link: https://arxiv.org/pdf/2309.02144.pdf

This paper proposes a constrained preference alignment method to improve the reasoning ability of LLMs.

[2] Math-Shepherd: A Label-Free Step-by-Step Verifier for LLMs in Mathematical Reasoning
Link: https://arxiv.org/pdf/2312.08935.pdf
This paper proposes a framework to automatical construct the training dataset of process reward models.

Thank you for your consideration. 😊

**Comment by chuanyang-Zheng** [comment]
Thank you very much for your notice. We have added the two papers to the survey. And we will further notice you after the next round paper update on arxiv.

If there are any questions, please let us know.

Again, thank you very much for your attention to our work, and thank you for your notice.

**Comment by Wangpeiyi9979** [comment]
Thanks!

**Comment by chuanyang-Zheng** [comment]
The update version is here. https://arxiv.org/abs/2312.11562 

If there are any questions, please let us know.

Again, thank you very much for your attention to our work, and thank you for your notice.
